### ISSUE TITLE
Fix bugs in PLUTO null graph for some versions

### ISSUE THREAD

**Issue by Oysters1874** [NYCPlanning/data-engineering-qaqc#100]
When selecting some earlier versions of PLUTO where has no null mismatch record, the page will throw an error saying list index out of range. 
<img width="655" alt="image" src="https://user-images.githubusercontent.com/44253950/180867588-7d028268-3fde-48e2-b368-fbd5ec4356e5.png">

**Comment by abrieff** [comment]
Think this is resolved, feel free to unclose if it's not
