### ISSUE TITLE
Pluto Mismatch Reports: Update Descriptions

### ISSUE THREAD

**Issue by abrieff** [NYCPlanning/data-engineering-qaqc#106]
From #78  
Update title of Mismatch graph -- finance to Mismatch graph -- finance fields / add fields to all titles
 Update the description below Mismatch graph -- finance to the following:

DOF updates the assessment and exempt values twice a year.  The tentative tax roll is released in mid-January and the final tax roll is released in late May.  We expect the values of the fields in the above graph to change in versions of PLUTO created after the release of the tentative or final roll.  For the PLUTO version created right after the tentative roll, most lots will show a change in assesstot, with a smaller number of changes for the assessland and exempttot.  There will also be changes to these fields in the version created after the release of the final roll.  Versions created between roll releases should see almost no change for these fields.

 Update the description below Mismatch graph -- area to the following:

CAMA is the primary source for the area fields. Updates reflect new construction, as well as updates by assessors for the tentative roll.  Several thousand lots may have updates in the version created after the tentative tax roll.
 Update the description below Mismatch graph -- building to the following:
Changes in these fields are most common after the tentative roll has been released. Several fields in this group are changed by DCP to improve data quality, including ownername and yearbuilt. When these changes are first applied, there will be a spike in the number of lots changed.

 Add description above or below table that is after the Mismatch graph -- building graph description.

This table reports the number of records with differences in a field value between versions.  This table is useful for digging into any anomalies identified using the graphs above.

**Comment by Oysters1874** [comment]
I think these descriptions look more readable to me, compared to the current version which is a stack of information. Just wondering whether we need to add any detailed information to those field names, such as assesstot, assessland. Or go back to what we have discussed before, provide users with a data dictionary tool.
