### ISSUE TITLE
DevDB QAQC: Spike Organization Ticket

### ISSUE THREAD

**Issue by abrieff** [NYCPlanning/data-engineering-qaqc#114]
# Proposed Work
### [DevDB Side](https://github.com/NYCPlanning/db-developments/issues/511)
Because the existing QAQC is immutable, we would like to build a new QAQC report on top of it, which would accomplish two main goals: filtering out records with no flags, and attaching additional variables (Job Type, Job Status, etc.) for filtering on the app side.
### [App Side](https://github.com/NYCPlanning/data-engineering-qaqc/issues/140)
Dataframe Display, with options to filter by key fields(Job Type, Job Status) and by flag type, to view the job numbers of records with each particular flag.

### [DevDB Side](https://github.com/NYCPlanning/db-developments/issues/518)
New report that includes one row per version, and totals the number of records flagged per QAQC check. 
### [App Side](https://github.com/NYCPlanning/data-engineering-qaqc/issues/144)
Graphs displaying the # of flagged records for each version and QAQC check

### [DevDB Side](https://github.com/NYCPlanning/db-developments/issues/513)
Could use some direction on the exact format of this - the idea of checking how the flags on records change over time, and how that maps onto the manual review process (ie: Excluding records that have been checked and are known to be fine or fixed)

### [DevDB Side](https://github.com/NYCPlanning/db-developments/issues/514)
For Job Status and Job Type, create a new report that includes the # of new records of each possible type created since the previous version, to be able to map over versions anomalies in the assigning of statuses or types
### [QAQC Side](https://github.com/NYCPlanning/data-engineering-qaqc/issues/145)
Graph for each field showing the distribution of new records by field value, with multiple lines for previous versions

### [DevDB Side](https://github.com/NYCPlanning/db-developments/issues/515)
There seem to be two separate checks here, one on a per-record basis, and one on the aggregate table.
1. For each record (perhaps to be included in the above new QAQC table) are the complete date, complete quarter and complete year all in alignment?)
2. What is the distribution of records by complete quarter? Are there any records with the most recent quarter present?
### [App Side](https://github.com/NYCPlanning/data-engineering-qaqc/issues/146)
Graph showing the distribution of completed records by quarter

### [DevDB Side](https://github.com/NYCPlanning/db-developments/issues/516)
Add an additional flag to the new QAQC table for checking that
classa_init - classa_prop = classa_net

### [App Side](https://github.com/NYCPlanning/data-engineering-qaqc/issues/147)
Graphs and Dataframe Displays of Manual Corrections Applied and Not Applied by field

**Comment by abrieff** [comment]
In our discussion, somehow I'd missed both [qaqc_units](https://github.com/NYCPlanning/db-developments/blob/main/sql/qaqc/qaqc_units.sql) and [final_qaqc](https://github.com/NYCPlanning/db-developments/blob/main/sql/qaqc/qaqc_final.sql) 

Seems like we're actually generating a ton of qaqc flags - do you know if these are a part of that dashboard you created, or something different?

**Comment by abrieff** [comment]
Existing Reports
## UNITS QAQC
This is a table that contains the job number and five boolean flags, with a row for every record in DevDB.

Columns
a. Job Number
b. Alteration where classa_net unit change < -5
c. New Building where the number of classa_prop proposed units > 499
d. Demolitions where there are larger than 19 classa_init units in the building
e. Whether its one of the 20 largest alterations by classa_net increase in units
f. Whether its one of the 20 largest alterations by classa_net decrease in units

No existing comparison across versions
### Proposed Work

Proposed Work:
New Report in DevDB with one row per version, that aggregates each of the five boolean flags to track change over time
Version Comparison Chart in QAQC to display the change between versions for each of these summary statistics
Tables in QAQC showing the records with each of these flags

**Comment by abrieff** [comment]
Linking to another past brainstorm about QAQC https://github.com/NYCPlanning/db-developments/issues/428

**Comment by abrieff** [comment]
linking to past work on getting hed input https://github.com/NYCPlanning/db-developments/issues/33 - some of the descriptions in the document may be worth re-evaluating for additional QAQC checks to add, but probably represents an avenue for v2 rather than initial page

**Comment by abrieff** [comment]
From HED:
Field Groupings:
Units, Class B, Outliers, Duplicates, Invalid Dates, Other, Geography, dem_nb_overlap

**Comment by abrieff** [comment]
Checking flags (as problematic) across versions -

**Comment by AmandaDoyle** [comment]
- Job_Type - change in number of records with each value between versions
- Job_Status  - change in number of records with each value between versions - use case job status not get created in latest version for example
- Complete_Year / Complete_Qrtr - does the current year/quarter exist in this field and are they aligned (i.e. December 2021 should map to 2021 Q4)
- Does ClassA_Init - ClassA_Prop = ClassA_Net?
- Occ_Initial - Occ_Proposed - is new value exist that's not in lookup table?

**Comment by abrieff** [comment]
# Proposed Work
## New QAQC Table
### DevDB Side
Because the existing QAQC is immutable, we would like to build a new QAQC report on top of it, which would accomplish two main goals: filtering out records with no flags, and attaching additional variables (Job Type, Job Status, etc.) for filtering on the app side.
### App Side
Dataframe Display, with options to filter by key fields(Job Type, Job Status) and by flag type, to view the job numbers of records with each particular flag.

## QAQC Version Aggregation Report
### DevDB Side
New report that includes one row per version, and totals the number of records flagged per QAQC check. 
### App Side
Graphs displaying the # of flagged records for each version and QAQC check

## QAQC Flag Change over Time
Could use some direction on the exact format of this - the idea of checking how the flags on records change over time, and how that maps onto the manual review process (ie: Excluding records that have been checked and are known to be fine or fixed)

## Field Distribution Reports
### DevDB Side
For Job Status and Job Type, create a new report that includes the # of new records of each possible type created since the previous version, to be able to map over versions anomalies in the assigning of statuses or types
### QAQC Side
Graph for each field showing the distribution of new records by field value, with multiple lines for previous versions

## Complete Year/Complete Quarter Report
### DevDB Side
There seem to be two separate checks here, one on a per-record basis, and one on the aggregate table.
1. For each record (perhaps to be included in the above new QAQC table) are the complete date, complete quarter and complete year all in alignment?)
2. What is the distribution of records by complete quarter? Are there any records with the most recent quarter present?
### App Side
Graph showing the distribution of completed records by quarter

**Comment by td928** [comment]
would it be okay for me to add my comments to your post @abrieff ?

**Comment by abrieff** [comment]
sure

**Comment by SashaWeinstein** [comment]
What does "display job number list for each of the qaqc checks" mean? Does that mean select a check and see all job numbers that are "yes" for that check?

**Comment by abrieff** [comment]
Yes

**Comment by SashaWeinstein** [comment]
Looking at 
>New Report in DevDB with one row per version, that aggregates each of the boolean flags to track change over time
Do we want this to work like pluto where each new version is appended to a table pulled down from the main folder in DO? This approach takes some time to implement (faster now that I've done it for pluto) but it's probably the most robust. It also allows us to compare the results of different branches for a given version.

**Comment by abrieff** [comment]
Yes, that was my thoughts for it

**Comment by SashaWeinstein** [comment]
Wrote up more of my thoughts on this subject https://github.com/NYCPlanning/db-developments/issues/518

**Comment by abrieff** [comment]
Perfect thank you

**Comment by damonmcc** [comment]
closing because all linked tasks are closed
