### ISSUE TITLE
Display number of difference instead of pct in pop up windows for PLUTO graphs 

### ISSUE THREAD

**Issue by mbh329** [NYCPlanning/data-engineering-qaqc#166]
Based on Lynn's suggestions:

"In the graphs, when you hover over a point and get a popup box, I'd prefer to see the number of differences, rather than the percentage"

**Comment by Oysters1874** [comment]
@mbh329 Hey, Max! Have your started looking into this? If not, I can take a look.

**Comment by mbh329** [comment]
@Oysters1874 I have not, feel free to get this going
