### ISSUE TITLE
COLP: Create Graphs and Display Number of Records by Agency/Usetype

### ISSUE THREAD

**Issue by Oysters1874** [NYCPlanning/data-engineering-qaqc#174]
For the COLP QAQC page, we would like to generate a clear graph to show number of records by agency/usetype. This can be similar to the CPDB QAQC.

**Comment by SashaWeinstein** [comment]
These charts will have only agency abbreviations. We want the full name somewhere, this [issue on the pipeline](https://github.com/NYCPlanning/db-colp/issues/217) is the way to address
