### ISSUE TITLE
Update mistune

### ISSUE THREAD

**Issue by mbh329** [NYCPlanning/data-engineering-qaqc#183]
Github flagged a critical issue with the mistune package

**Comment by mbh329** [comment]
@SashaWeinstein I think we have to deploy to main for this to work, would it be possible to do that today? happy to do it as well if you want to quickly go over how to do it

**Comment by SashaWeinstein** [comment]
What exactly do you mean by "work" here? I'm open to deploying but want to make sure I understand what's going on

**Comment by mbh329** [comment]
Ahh sorry I didn't follow up. When I meant "work" I meant that in order for the security alert to go away and test if the updating mistune "worked" than we probably have to merge dev into main. not sure if we have to redeploy the app though

**Comment by damonmcc** [comment]
closing because there are no security alerts at the moment
