### ISSUE TITLE
Digital ocean client dynamically constructs url

### ISSUE THREAD

**Issue by SashaWeinstein** [NYCPlanning/data-engineering-qaqc#220]
Does it make sense to construct the base of the url as `f"https://{bucket_name}.nyc3.digitaloceanspaces.com"` and do this in the client? I can make this improvement just wanted to get your thoughts @abrieff

**Comment by abrieff** [comment]
Yeah that seems right

**Comment by SashaWeinstein** [comment]
Out of date now that the digital ocean client uses boto3
