### ISSUE TITLE
Comparing Major vs Minor Releases in PLUTO 

### ISSUE THREAD

**Issue by mbh329** [NYCPlanning/data-engineering-qaqc#249]
We need to discuss how we see the comparisons across versions changing (or staying the same) with the new addition of the minor releases of PLUTO In its current iteration,

**Comment by damonmcc** [comment]
linking to [recent discussion of this topic](https://github.com/NYCPlanning/data-engineering-qaqc/pull/254#issuecomment-1466964718)

**Comment by damonmcc** [comment]
closing in favor of #255
