### ISSUE TITLE
Add version 22v1 to PLUTO QAQC

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/data-engineering-qaqc#25]
Add version 22v1 to PLUTO QAQC so that app can work.  In [this series](https://github.com/NYCPlanning/data-engineering-qaqc/blob/3c0134bb6abe45b7884c9459878a92ec976d2e00/src/pluto.py#L88) add 22v1, 22v2, 22v3, etc.  I'd suggest going into 23v1.

**Comment by abrieff** [comment]
Believe this has been done, closing
