### ISSUE TITLE
Workflow dispatch button for deployment action

### ISSUE THREAD

**Issue by SashaWeinstein** [NYCPlanning/data-engineering-qaqc#33]
The actions page in the repo doesn't have the button to run the deployment workflow

**Comment by mbh329** [comment]
Was able to get the workflow dispatch button to appear by updating the `main.yml` on the master branch but I am not able to run the workflow dispatch off  the dev branch, it fails in the deploy step.

**Comment by SashaWeinstein** [comment]
frustrating, I know what the issue is and I thought I updated the feature branch. the issue is that I updated the name of a secret to `DOKKU_SSH_KEY`. I made the correct change and pushed the result, and am re-running the action
