### ISSUE TITLE
Outdated log markdown file

### ISSUE THREAD

**Issue by SashaWeinstein** [NYCPlanning/data-engineering-qaqc#45]
The pluto QAQC `get_data` function has these lines
```python
log = requests.get(
    "https://raw.githubusercontent.com/NYCPlanning/db-pluto/master/maintenance/log.md"
).text
```
There is no maintenance folder in the root of the pluto repo anymore so this just gets a 404. @AmandaDoyle I'm curious if you know what was in this markdown and whether we should think about fixing this or just delete it.

**Comment by AmandaDoyle** [comment]
log.md can get blown away.  [This](https://github.com/NYCPlanning/db-pluto/commit/6d5a08a8d9559aabb618a87d39e264fd6bec5d29) is what it used to contain, but with the adoption of GitHub Actions and using issues to trigger a build this became antiquated.

**Comment by SashaWeinstein** [comment]
Interesting
