### ISSUE TITLE
Add CPDB Page

### ISSUE THREAD

**Issue by SashaWeinstein** [NYCPlanning/data-engineering-qaqc#46]
Add two tables `cpdb_summarystats_magency` and `cpdb_summarystats_sagency`. Maybe add filters, sorting and/or color coding. We will pair code through this as a group

**Comment by td928** [comment]
@SashaWeinstein just want to flag that the pair coding session the other day should pretty much covers this and the branch currently does not seem to have all the changes we made the other day.

**Comment by SashaWeinstein** [comment]
Nice flag, let me push right now. Do you think it makes sense to open a PR with that work and close this issue? And if someone wants to pick up this work they create a new feature branch

**Comment by SashaWeinstein** [comment]
My local is up to date with remote and I see all the work I did on github
