### ISSUE TITLE
Corrections Summary

### ISSUE THREAD

**Issue by SashaWeinstein** [NYCPlanning/data-engineering-qaqc#49]
From Lynn's wishlist:
> For each field that has manual corrections 
> - Number of changes made  
> - Number of changes not applied (because oldvalue did not match) 
>
> Compare with previous version 

I think the top two bullet points should be fairly easy. There is already a `pluto_corrections.zip` file uploaded to DO that may have all the info we need.

Comparing versions will be harder so I would focus on the top two bullet points first. Best to avoid any processing on the app side so a new table to compare corrections across versions should be implemented in pluto to create this table or set of tables

**Comment by abrieff** [comment]
I'm confused about the second bullet point about corrections not applied - is this something we currently track for pluto? What does it mean in this context

**Comment by SashaWeinstein** [comment]
Curious if anyone in @NYCPlanning/data-engineering who has worked more with PLUTO corrections has thoughts on this

**Comment by abrieff** [comment]
Closing this issue and creating a new one for the previous version comparison
