### ISSUE TITLE
Outlier Report

### ISSUE THREAD

**Issue by SashaWeinstein** [NYCPlanning/data-engineering-qaqc#50]
From Lynn's wishlist
> - BBLs where building area more than doubled since previous version 
> - BBLs with 50+ unitsres and resarea/unitsres < 300 
> - BBL's where bldgarea/lotarea  > numfloors*2 

This is a fairly hard upgrade as we don't have logic to identify these bbl's nor an established way to display them in a readable way on the front-end. It would definitely be ok to just implement some of those checks and/or come up with some on your own. Something is better than nothing and finding a way to succinctly summarize outliers is more important than covering each check on the first try

**Comment by abrieff** [comment]
Think this is resolved, feel free to unclose if it's not
