### ISSUE TITLE
`setup.py` Issues

### ISSUE THREAD

**Issue by mbh329** [NYCPlanning/data-engineering-qaqc#57]
With the recent additions to the qaqc page, I was having difficulties accessing the qaqc app locally (no module errors for `boto3 and `python-dotenv` ).  The `dev` branch has an outdated setup.py file so when you branch off of these you consistently have issues viewing the latest changes to the qaqc app if you don't rebuild the dev container with the necessary modules (i.e. boto3 and python-dotenv).  

In @SashaWeinstein 41-PLUTO-to-DO branch there is an updated setup.py file but I was unable to rebuild my container successfully with json installation because that is a built in module for python. After removing it, I can now successfully rebuild the container and view the latest changes

Did anyone else have these issues?

**Comment by Oysters1874** [comment]
I didn't try it on the dev branch. I just directly tried it on Sasha's 41-PLUTO-to-DO branch. I also have to remove the json file and install the boto3 to make it work.
