### ISSUE TITLE
CPDB Geometries Visualization

### ISSUE THREAD

**Issue by td928** [NYCPlanning/data-engineering-qaqc#86]
Copy over from Amanda's comment in #73 

Show a map of all point and polygon geometries in the current CPDB. This will allow someone to eyeball any egregiously wrong geometries (i.e. polygon that covers all of NYC or lines that are really harsh, like we saw in the "noodle" issue)

Some thinking might need to be done on how to best show this on a map i.e. with all the points and polygon overlapping might be difficult to catch the weirdness going on with geometries. Maybe two maps are a solution or some toggle functionality to switch between all points vs. all polygons.

**Comment by abrieff** [comment]
Can I verify that these two files 
```
    SHP_export cpdb_dcpattributes_pts MULTIPOINT &
    SHP_export cpdb_dcpattributes_poly MULTIPOLYGON 
```
are the ones that we want to visualize?

**Comment by td928** [comment]
hey @abrieff would you point me to the feature branch your work is on for this?

**Comment by abrieff** [comment]
@td928 https://github.com/NYCPlanning/data-engineering-qaqc/compare/dev...86-geometries-visualization?expand=1 didnt get very far
