### ISSUE TITLE
App Refactor: Using Components to Encapsulate QAQC report logic

### ISSUE THREAD

**Issue by abrieff** [NYCPlanning/data-engineering-qaqc#96]
Currently, each application page is defined in one file (pluto.py, facdb.py) etc. Each component section, usually consisting of 
1. Loading data
2. Manipulating Data
3. Displaying Data
4. Headers, markdown and other info

Is either written at the root function level, or encapsulated in a series of nested functions. While there are some benefits to having all of this logic in one place, doing so makes concurrent development more difficult, the files themselves quite difficult to read and debug, and does not feel very maintainable with a larger set of reports, especially as we start to place different reports in different subpages. It also makes it more difficult to catch error messages, as right now if there are errors anywhere on the page, it crashes the entire page. 

I'm recommending that we create a new components folder within each app directory, with new files named for the specific report or graph they display. These would make editing individual reports less risky, make the code more readable (pluto.py would become just responsible for laying out where the different reports should go), make adding future reports easier, and allow each component of the application to more easily follow the single responsibility principle.

ie: ` / pluto/components/mismatch_report.py `

One option for organizing this is to have each component create, write to and return an st.container, which encapsulates an invisible section of the page.

https://docs.streamlit.io/library/api-reference/layout/st.container

We could write these components to either 
1. Be self-sufficient, and pull their own data from s3 by using an imported function from helpers.py. The benefits of this are to make these components completely ignorant of context - you could decide to easily make one page with top-level checks from a number of different applications, for example. You also might be better able to take advantage of the streamlit caching mechanism, where the results of an individual report are cached so if a different report changes, it doesn't have to be reloaded.
2. Take in a report as an argument, leaving the current get_data function alone and leaving that logic as is. This is probably the right approach to start with because it limits changes, with option 1 being a potential future enhancement.

**Comment by SashaWeinstein** [comment]
Thanks for writing this up! I definitely think this is a necessary change for the pluto change and best practice going forward for other changes

**Comment by mbh329** [comment]
Yeah this is great! Taking a look at the pluto page as is if definitely a bit overwhelming and the current lay out has hindered development as we work concurrently on each page.

**Comment by abrieff** [comment]
closing this as the process has been started.
